export const questionsData = {
    response_code: 0,
    results: [
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "At the end of the 2001 film &quot;Rat Race&quot;, whose concert do the contestants crash?",
        correct_answer: "Smash Mouth",
        incorrect_answers: ["Bowling for Soup", "Sum 41", "Linkin Park"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "Who played the female lead in the 1933 film &quot;King Kong&quot;?",
        correct_answer: "Fay Wray",
        incorrect_answers: ["Jean Harlow", "Vivien Leigh", "Mae West"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "Who is the main protagonist in, the 1985 film, Back to the Future?",
        correct_answer: "Marty McFly",
        incorrect_answers: ["Emmett &quot;Doc&quot; Brown", "Biff Tannen", "George McFly"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "In the Super Mario Bros. Movie (2023), who plays Toad?",
        correct_answer: "Keegan-Michael Key",
        incorrect_answers: ["Seth Rogan", "Charlie Day", "Jack Black"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "Who directed the 2015 movie &quot;The Revenant&quot;?",
        correct_answer: "Alejandro G. I&ntilde;&aacute;rritu",
        incorrect_answers: ["Christopher Nolan", "David Fincher", "Wes Anderson"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "Which of these Movies was NOT released in 1996?",
        correct_answer: "Gladiator",
        incorrect_answers: ["Independence Day", "The Rock", "Mission: Impossible"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "What was the first James Bond film?",
        correct_answer: "Dr. No",
        incorrect_answers: ["Goldfinger", "From Russia With Love", "Thunderball"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question:
          "Which of these actors/actresses is NOT a part of the cast for the 2016 movie &quot;Suicide Squad&quot;?",
        correct_answer: "Scarlett Johansson",
        incorrect_answers: ["Jared Leto", "Will Smith", "Margot Robbie"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "In the movie Gremlins, after what time of day should you not feed Mogwai?",
        correct_answer: "Midnight",
        incorrect_answers: ["Evening", "Morning", "Afternoon"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Entertainment: Film",
        question: "Who played Deputy Marshal Samuel Gerard in the 1993 film &quot;The Fugitive&quot;?",
        correct_answer: "Tommy Lee Jones",
        incorrect_answers: ["Harrison Ford", "Harvey Keitel", "Martin Landau"],
      },
    ],
  };
  